export { default as Navbar } from './Navbar/Navbar'
export { default as Solutions } from './Solutions/Solutions'
export { default as About } from './About/About'
export { default as ContactForm } from './ContactForm/ContactForm'
export { default as Footer } from './Footer/Footer'
export { default as Chatbot } from './Chatbot/Chatbot'
