export { default as Navbar } from './Navbar/Navbar'
export { default as Slogan } from './Slogan/Slogan'
export { default as Solutions } from './Solutions/Solutions'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'
